within EU_CleanSky.EDS.Utilities.HierarchicalConnection.Aircraft.Internal;
connector Pin
  "Variant of Modelica.Electrical.Analog.Interfaces.Pin with a RootFinder"
  extends Modelica.Electrical.Analog.Interfaces.Pin;
  RootFinder root;
  annotation (Icon(graphics={ Rectangle(
          extent={{-100,100},{100,-100}},
          lineColor={0,0,255},
          fillColor={0,0,255},
          fillPattern=FillPattern.Solid)}), Documentation(info="<html>
<p>See the Documentation of<a href=\"modelica://RootFinder\"> </a><a href=\"modelica://EU_CleanSky.EDS.Utilities.HierarchicalConnection.Aircraft.Internal.RootFinder\">EU_CleanSky.EDS.Utilities.HierarchicalConnection.Aircraft.Internal.RootFinder</a> for the general principles.</p>
<p>Pin is a standard connector, with just &apos;v&apos; as the potential variable and &apos;i&apos; as the flow variable. &apos;finder&apos; does not add any unknown to the connector, but instead triggers the root finding algorithm in the Modelica translation tool. The algorithm considers in turn each connection graph of this type and derives spanning tree structures from these graphs through the choice of a root and the elimination of ordinary breakable connects. The virtual connection graph in the simplest case of the hierarchical connector (HC) is identical to the connection set, and includes for each Pin connector defined in the HC, the connector &apos;hierarchy&apos; which is declared in the &apos;PartialContext&apos; diagram base model, and all the Proxies refering to that connector. </p>
<p>In the case of a complex hierarchy with several intermediate HC of the same or different types, the connection set also includes the &apos;internal&apos; connector which is declared in &apos;PartialSubsystem&apos;, the level above &apos;PartialContext&apos;. &apos;PartialSubsystem&apos; and all the derived models are conceptually proxies as well, even though they connect to the entire HC rather than just one connector (the Proxy also connects to the whole HC, then extracts one connector). So the virtual connection graph can include other hierarchical connectors as well and may form a complex tree structure reflecting in part the hierarchical construction of the whole model. </p>
<p>In that structure of interconnected HierarchicalConnection.Aircraft.Internal.Pin nodes, the RootFinder will allocate exactly one Root node. The Root node will be randomly chosen among those nodes having the lowest number of other connections, and if this number is zero at the chosen Root, we will know that the whole virtual connection graph is unconnected. Such a graph can easily occur is a connector is declared in a HC, but later remains unused. Because &apos;PartialSubsystem&apos; instances count as unconnected proxies for all the connectors which are not used in that particular Subsystem, the situation is very common and, if untreated, would prevent most models from translating. The <a href=\"modelica://EU_CleanSky.EDS.Utilities.HierarchicalConnection.Example\">Example</a> relying on the Base library is too simple to have this issue: all the subsystems use both pins defined in the HC.</p>
<p>As explained in the documentation of RootFinder, such connection graphs have one too many flow equations, and one missing potential equation. All the potentials are equal, but there is no equation to set the potential. At the root, when we detect that the whole connection graph is unconnected, instead of defining a zero-flow condition, we define a null potential condition which balances the number of equations and the number of unknowns for both flow and potential variables.</p>
</html>"));
end Pin;
